title: "Managing Research Software Projects"
domain: "https://codebender.org"
repository: gvwilson/codebender
author: "Greg Wilson"

logo: "/static/codebender.svg"

exclude:
  - README.md
  - Makefile
  - "bin/*"
  - "*.aux"
  - "*.bbl"
  - "*.blg"
  - "*.log"
  - "*.out"
  - "*.pdf"
  - "*.tex"

lessons:
  - section: "Day 1"
  - slug: "introduction"
    title: "Introduction"
    lede: "Who you are, who's teaching this workshop, what we're going to cover, and how to participate."
    time: 15
  - slug: "governance"
    title: "Governance"
    lede: "Figuring out who gets to decide what and how to tell when a decision has been made."
    time: 60
  - break: 15
  - slug: communication
    title: "Communication"
    lede: "How to help people understand what you're doing and how to use what you've built."
    time: 45
  - slug: "workflow"
    title: "Workflow"
    lede: "Managing who does what and when."
    time: 30
  - break: 15
  - slug: "newcomers"
    title: "Newcomers"
    lede: "How to attract new contributors and help them feel welcome and be productive."
    time: 60
  - section: "Day 2"
  - slug: "design"
    title: "Design"
    lede: "Guidelines for creating software that is maintainable and reliable."
    time: 60
  - break: 15
  - slug: mechanics
    title: "Mechanics"
    lede: "The structure and operation of a medium-sized research software project."
    time: 60
  - break: 15
  - slug: leadership
    title: "Leadership"
    lede: "Things you need to do now that you're in charge."
    time: 60
  - slug: "change"
    title: "Change"
    lede: "Because sometimes the only way to fix a problem is to fix the institution."
    time: 30

advice:
  - slug: "engineering"
    title: "Software Engineering"
    lede: "What we actually know about (building) software and why we believe it's true."
  - slug: "robustness"
    title: "Robustness"
    lede: "Making research software robust enough to be run by anyone, anywhere."
  - slug: "partnering"
    title: "Partnering"
    lede: "Building good working relationships between academia and industry."
  - slug: "findability"
    title: "Findability"
    lede: "There's no point building it if people can't find it."
  - slug: "safety"
    title: "Online Safety"
    lede: "Being a leader doesn't have to mean being a target."
  - slug: "being-fired"
    title: "Being Fired"
    lede: "Departure isn't always voluntary."
  - slug: "moving-on"
    title: "Moving On"
    lede: "Because every new beginning comes from some other beginning's end."

extras:
  - slug: "license"
    title: "License"
    lede: "You can re-use this material however you want so long as you cite this as the original source."
  - slug: "conduct"
    title: "Code of Conduct"
    lede: "Everyone is welcome to take part provided they are respectful of others."
  - slug: "contributing"
    title: "Contributing"
    lede: "How to get set up and make a contribution."
  - slug: "bibliography"
    title: "Bibliography"
    lede: "The sources that inspired and informed this work."
  - slug: "glossary"
    title: "Glossary"
    lede: "Terms used in this work."
  - slug: "credits"
    title: "Credits"
    lede: "Who has contributed and why you should trust them."
