This workshop is a short introduction to organizational change
for people with backgrounds in research.
All of the material is available under an open license,
and contributions through our repository are welcome.
All contributors are required to respect our Code of Conduct.

## Learner Persona

-   Sabina, 28, has a master's degree in animal physiology
    and now works as a data analyst for a mid-sized pharmaceutical company.
-   She takes open access publishing and open source software for granted,
    but has never been involved in politics or advocacy beyond signing a few online petitions.
-   Sabina's company doesn't have a policy on staff contributing to open source projects,
    and the head of her department occasionally grumbles about
    "all this diversity stuff" distracting people from "real work".
    She wants unambiguous permission for the former and official company support for the latter.
-   Sabina doesn't mind public speaking,
    but finds face-to-face conflict very stressful.

This workshop teaches Sabina the basics of organizational change,
while the exercises help her figure out what changes she wants
and how to achieve them.
